packages:
  - 'packages/*'

catalogs:
  common:
    '@types/react': latest
    '@types/react-dom': latest
    '@vitejs/plugin-react': latest
    'autoprefixer': latest
    'postcss': latest
    'react': latest
    'react-dom': latest
    'typescript': latest
    'vite': latest
  tailwindcss3:
    'tailwindcss': ^3.4.17
  tailwindcss4:
    'tailwindcss': latest
    '@tailwindcss/postcss': latest
    '@tailwindcss/vite': latest
  tailwindmerge:
    'tailwind-merge': latest
