packages:
  - 'packages/*'

catalogs:
  common:
    '@types/react': ^19.0.8
    '@types/react-dom': ^19.0.3
    '@vitejs/plugin-react': ^4.3.4
    'autoprefixer': ^10.4.20
    'postcss': ^8.5.1
    'react': ^19.0.0
    'react-dom': ^19.0.0
    'typescript': ^5.6.2
    'vite': ^6.0.5
  tailwindcss3:
    'tailwindcss': ^3.4.17
  tailwindcss4:
    'tailwindcss': ^4.0.1
    '@tailwindcss/postcss': ^4.0.1
    '@tailwindcss/vite': ^4.0.1
  tailwindmerge:
    'tailwind-merge': ^3.0.1
